# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rfolly_malloc_stats_print <- function() {
    .Call(`_rfolly_rfolly_malloc_stats_print`)
}

small_vector_test <- function() {
    invisible(.Call(`_rfolly_small_vector_test`))
}

